=== Notarise-gov-sg/api-notarise-healthcerts/src/static/schema/pdt-healthcert-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schemata.openattestation.com/sg/gov/moh/pdt-healthcert/2.0/schema.json",
  "type": "object",
  "required": ["id", "version", "type", "validFrom", "fhirVersion", "fhirBundle"],
  "definitions": {
    "PdtTypes": {
      "type": "string",
      "enum": ["PCR", "ART", "SER", "LAMP"]
    }
  },
  "properties": {
    "id": {
      "type": "string",
      "examples": ["TEST001"]
    },
    "version": {
      "type": "string",
      "enum": ["pdt-healthcert-v2.0"]
    },
    "type": {
      "oneOf": [
        { "$ref": "#/definitions/PdtTypes" },
        {
          "type": "array",
          "items": { "$ref": "#/definitions/PdtTypes" },
          "uniqueItems": true,
          "minItems": 1
        }
      ]
    },
    "logo": {
      "type": "string",
      "description": "base64 encoded image"
    },
    "validFrom": {
      "type": "string",
      "format": "date-time",
      "description": "Date and time from which the document is considered valid"
    },
    "fhirVersion": {
      "type": "string",
      "examples": ["4.0.1"]
    },
    "fhirBundle": {
      "$ref": "https://schemata.openattestation.com/sg/gov/moh/fhir/4.0.1/lite-schema.json#/definitions/Bundle",
      "description": "FHIR bundle for a collection of resources. Each resource and the entire bundle should be compliant against the base spec of FHIR. You may use a validator like: https://inferno.healthit.gov/validator/"
    }
  }
}

=== Notarise-gov-sg/api-notarise-healthcerts/test/fixtures/v2/pdt_art_unwrapped.json
{
  "id": "340139b0-8e92-4ed6-a589-d54730f52963",
  "version": "pdt-healthcert-v2.0",
  "type": "ART",
  "validFrom": "2021-05-18T06:43:12.152Z",
  "fhirVersion": "4.0.1",
  "fhirBundle": {
    "resourceType": "Bundle",
    "type": "collection",
    "entry": [
      {
        "fullUrl": "urn:uuid:ba7b7c8d-c509-4d9d-be4e-f99b6de29e23",
        "resource": {
          "resourceType": "Patient",
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/patient-nationality",
              "extension": [
                {
                  "url": "code",
                  "valueCodeableConcept": {
                    "text": "Patient Nationality",
                    "coding": [
                      {
                        "system": "urn:iso:std:iso:3166",
                        "code": "SG"
                      }
                    ]
                  }
                }
              ]
            }
          ],
          "identifier": [
            {
              "id": "PPN",
              "type": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                    "code": "PPN",
                    "display": "Passport Number"
                  }
                ]
              },
              "value": "E7831177G"
            },
            {
              "id": "NRIC-FIN",
              "value": "S9098989Z"
            }
          ],
          "name": [
            {
              "text": "Tan Chen Chen"
            }
          ],
          "gender": "female",
          "birthDate": "1990-01-15"
        }
      },
      {
        "fullUrl": "urn:uuid:0275bfaf-48fb-44e0-80cd-9c504f80e6ae",
        "resource": {
          "resourceType": "Specimen",
          "subject": {
            "type": "Device",
            "reference": "urn:uuid:9103a5c8-5957-40f5-85a1-e6633e890777"
          },
          "type": {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "258500001",
                "display": "Nasopharyngeal swab"
              }
            ]
          },
          "collection": {
            "collectedDateTime": "2020-09-27T06:15:00Z"
          }
        }
      },
      {
        "fullUrl": "urn:uuid:7729970e-ab26-469f-b3e5-36a42ec24146",
        "resource": {
          "resourceType": "Observation",
          "performer": [
            {
              "type": "Practitioner",
              "reference": "urn:uuid:3dbff0de-d4a4-4e1d-98bf-af7428b8a04b"
            },
            {
              "id": "LHP",
              "type": "Organization",
              "reference": "urn:uuid:fa2328af-4882-4eaa-8c28-66dab46950f1"
            }
          ],
          "identifier": [
            {
              "id": "ACSN",
              "type": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                    "code": "ACSN",
                    "display": "Accession ID"
                  }
                ]
              },
              "value": "123456789"
            }
          ],
          "category": [
            {
              "coding": [
                {
                  "system": "http://snomed.info/sct",
                  "code": "840539006",
                  "display": "COVID-19"
                }
              ]
            }
          ],
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "94531-1",
                "display": "SARS-CoV-2 (COVID-19) RNA panel - Respiratory specimen by NAA with probe detection"
              }
            ]
          },
          "valueCodeableConcept": {
            "coding": [
              {
                "system": "http://snomed.info/sct",
                "code": "260385009",
                "display": "Negative"
              }
            ]
          },
          "effectiveDateTime": "2020-09-28T06:15:00Z",
          "status": "final"
        }
      },
      {
        "fullUrl": "urn:uuid:3dbff0de-d4a4-4e1d-98bf-af7428b8a04b",
        "resource": {
          "resourceType": "Practitioner",
          "name": [{ "text": "Dr Michael Lim" }],
          "qualification": [
            {
              "code": {
                "coding": [
                  {
                    "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                    "code": "MCR",
                    "display": "Practitioner Medicare number"
                  }
                ]
              },
              "identifier": [
                {
                  "id": "MCR",
                  "value": "123456"
                }
              ],
              "issuer": {
                "type": "Organization",
                "reference": "urn:uuid:bc7065ee-42aa-473a-a614-afd8a7b30b1e"
              }
            }
          ]
        }
      },
      {
        "fullUrl": "urn:uuid:bc7065ee-42aa-473a-a614-afd8a7b30b1e",
        "resource": {
          "resourceType": "Organization",
          "name": "Ministry of Health (MOH)",
          "type": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                  "code": "govt",
                  "display": "Government"
                }
              ]
            }
          ],
          "contact": [
            {
              "telecom": [
                { "system": "url", "value": "https://www.moh.gov.sg" },
                { "system": "phone", "value": "+6563259220" }
              ],
              "address": {
                "type": "physical",
                "use": "work",
                "text": "Ministry of Health, 16 College Road, College of Medicine Building, Singapore 169854"
              }
            }
          ]
        }
      },
      {
        "fullUrl": "urn:uuid:fa2328af-4882-4eaa-8c28-66dab46950f1",
        "resource": {
          "resourceType": "Organization",
          "name": "MacRitchie Medical Clinic",
          "type": [
            {
              "coding": [
                {
                  "system": "http://terminology.hl7.org/CodeSystem/organization-type",
                  "code": "prov",
                  "display": "Healthcare Provider"
                }
              ],
              "text": "Licensed Healthcare Provider"
            }
          ],
          "contact": [
            {
              "telecom": [
                {
                  "system": "url",
                  "value": "https://www.macritchieclinic.com.sg"
                },
                { "system": "phone", "value": "+6561234567" }
              ],
              "address": {
                "type": "physical",
                "use": "work",
                "text": "MacRitchie Hospital, Thomson Road, Singapore 123000"
              }
            }
          ]
        }
      },
      {
        "fullUrl": "urn:uuid:9103a5c8-5957-40f5-85a1-e6633e890777",
        "resource": {
          "resourceType": "Device",
          "type": {
            "coding": [
              {
                "system": "https://covid-19-diagnostics.jrc.ec.europa.eu/devices",
                "code": "1232",
                "display": "Abbott Rapid Diagnostics, Panbio COVID-19 Ag Rapid Test"
              }
            ]
          }
        }
      }
    ]
  }
}
